steps:
  # -------------------------------------------------------------------------
  # 1. PREPARE CACHE (Parallel)
  # -------------------------------------------------------------------------
  
  # 1a. Pull previous Backend image for caching (Parallel)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:latest || true']
    waitFor: ['-']
    id: 'Pull Backend Cache'

  # 1b. Pull previous Frontend image for caching (Parallel)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:latest || true']
    waitFor: ['-']
    id: 'Pull Frontend Cache'

  # 1c. Run Tests (Parallel with cache pulling)
  # Runs on the host VM while images are pulling/building
  - name: 'python:3.11'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        pip install -r app/backend/requirements.txt
        export PYTHONPATH=$$PYTHONPATH:.
        pytest tests/
    env:
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - 'GCS_BUCKET_NAME=${_BUCKET_NAME}'
      - 'STORAGE_TYPE=gcs'
    waitFor: ['-']
    id: 'Run Unit & E2E Tests'

  # -------------------------------------------------------------------------
  # 2. BUILD (Parallel)
  # -------------------------------------------------------------------------

  # 2a. Build Backend Image
  # Uses the mirrored base image and cache-from
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:latest'
      - '--build-arg'
      - 'BASE_IMAGE=${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-texlive-base:latest'
      - '-f'
      - 'app/backend/Dockerfile'
      - '.'
    waitFor: ['Pull Backend Cache']
    id: 'Build Backend'

  # 2b. Build Frontend Image
  # Uses cache-from
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:latest'
      - '-f'
      - 'app/frontend/Dockerfile'
      - '.'
    waitFor: ['Pull Frontend Cache']
    id: 'Build Frontend'

  # -------------------------------------------------------------------------
  # 3. PUSH (Parallel)
  # -------------------------------------------------------------------------

  # 3a. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:$BUILD_ID']
    waitFor: ['Build Backend', 'Run Unit & E2E Tests']
    id: 'Push Backend'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:latest']
    waitFor: ['Build Backend', 'Run Unit & E2E Tests']
    id: 'Push Backend Latest'

  # 3b. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:$BUILD_ID']
    waitFor: ['Build Frontend', 'Run Unit & E2E Tests']
    id: 'Push Frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:latest']
    waitFor: ['Build Frontend', 'Run Unit & E2E Tests']
    id: 'Push Frontend Latest'

  # -------------------------------------------------------------------------
  # 4. DEPLOY (Sequential)
  # -------------------------------------------------------------------------

  # 4a. Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'readpaper-backend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
      - '--set-env-vars'
      - 'GCS_BUCKET_NAME=${_BUCKET_NAME},GEMINI_API_KEY=${_GEMINI_API_KEY},STORAGE_TYPE=gcs,GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},DISABLE_AUTH=false'
    waitFor: ['Push Backend']
    id: 'Deploy Backend'

  # 4b. Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        # Use stable Cloud Run URL pattern (PROJECT_NUMBER.REGION.run.app).
        BACKEND_URL="https://readpaper-backend-989182646968.us-central1.run.app"
        FRONTEND_URL="https://readpaper-frontend-989182646968.us-central1.run.app"
        
        echo "Backend URL: $$BACKEND_URL"
        echo "Frontend URL: $$FRONTEND_URL"
        
        # IMPORTANT: Use a stable NEXTAUTH_SECRET so sessions survive across deploys.
        # If this is randomized per deploy, all user sessions are invalidated on every push.
        gcloud run deploy readpaper-frontend \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "API_URL=$$BACKEND_URL,NEXT_PUBLIC_API_URL=$$BACKEND_URL,AUTH_TRUST_HOST=true,NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},AUTH_GOOGLE_ID=${_GOOGLE_CLIENT_ID},AUTH_GOOGLE_SECRET=${_GOOGLE_CLIENT_SECRET},NEXTAUTH_URL=$$FRONTEND_URL,AUTH_URL=$$FRONTEND_URL,NEXT_PUBLIC_DISABLE_AUTH=false"
    waitFor: ['Push Frontend', 'Deploy Backend']
    id: 'Deploy Frontend'

substitutions:
  _REGION: 'us-central1'
  _BUCKET_NAME: 'readpaper-storage-gen-lang-client-0098594892'
  _GOOGLE_CLIENT_ID: 'MUST_BE_PROVIDED'
  _GOOGLE_CLIENT_SECRET: 'MUST_BE_PROVIDED'
  # IMPORTANT: Use a FIXED stable value here. Do NOT randomize per deploy.
  # Changing this secret invalidates all existing user sessions.
  _NEXTAUTH_SECRET: 'MUST_BE_PROVIDED'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-backend:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/readpaper-repo/readpaper-frontend:latest'

options:

  logging: CLOUD_LOGGING_ONLY

  machineType: 'E2_HIGHCPU_8'
